### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by n8henrie** [simlay/swift-rust-xcode-template#2]
Thank you for this excellent template!

I've forked and added several changes at <https://github.com/n8henrie/swift-rust-xcode-template>, including the removal of cargo-lipo, trying to use cargo-generate's templating throughout (instead of `rename.sh`), and externalizing the build script.

Just thought you might be interested. I am a novice at XCode and new to iOS development, so I'm sure it is not following best practices. I plan to keep it as a separate fork, but I'd happily make a PR here if you are interested in merging the changes.

Thanks again! Will close shortly as this isn't a "real" issue.

**Comment by simlay** [comment]
Awe thanks! I'm glad you found it helpful! I authored this template a long time ago and the tooling for rust swift interop has gotten a lot better (or maybe I've learned a lot). My current task, (https://github.com/liveview-native/liveview-native-core/pull/43) uses uniffi to generate high level swift/kotlin from rust.

Also, if you're trying to test random rust in an iOS simulator, you can use [`cargo-dinghy`](https://github.com/sonos/dinghy) as a runner. I should look into adding watchos and tvos support to dinghy.

**Comment by n8henrie** [comment]
The rust-swift uniffy interop looks so cool, I just learned about it last week (some HN post I think), can't wait to give it a shot! 

Thanks for the suggestions, I will check those out.
